---
grails:
    profile: web
    codegen:
        defaultPackage: gestion
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.xml'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 3072000
            maxRequestSize: 3072000
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none
    plugin:
        springsecurity:
            oauth2:
                active: true
                registration:
                    roleNames: ['ROLE_USER']
                providers:
                    google:
                        api_key: '913695137763-den74ink8k1a51kf42de5m875b7mopen.apps.googleusercontent.com'               #needed
                        api_secret: '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'         #needed
                        successUri: "/oauth2/google/success"    #optional
                        failureUri: "/oauth2/google/failure"    #optional
                        callback: "/oauth2/google/callback"     #optional
                        scopes: 'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email'
#management:
#    endpoints:
#        jmx:
#            unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
    username: "root"
    password: ''
environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/gestion?autoReconnect=true&useSSL=false&serverTimezone=-0300&useLegacyDatetimeCode=false
#            username: "root"
#            password: 'Gol220022@'
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: "update"
            #            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            url: "jdbc:mysql://localhost:3306/gestion_beta?autoReconnect=true&useSSL=false&serverTimezone=-0300&useLegacyDatetimeCode=false"
            username: "root"
            password: 'Gol220022@'
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

#grails:
#    mail:
#        host: "mail.somosgol.cl"
#        port: "587"
#        username: "notificaciones@somosgol.cl"
#        password: "Gol220022@"
#        from: "Notificaciones<notificaciones@somosgol.cl>"
#        props:
#            mail.smtp.auth: "true"
#            mail.smtp.starttls.enable: "true"
#            mail.smtp.connectiontimeout: "10000"
##         mail.debug: "true"
grails:
    mail:
        host: "mail.bookeame.cl"
        port: "587"
        username: "noresponder@bookeame.cl"
        password: "Gol220022@"
        from: "Bookeame<noresponder@bookeame.cl>"
        props:
            mail.smtp.auth: "true"
            mail.smtp.starttls.enable: "true"
            mail.smtp.connectiontimeout: "10000"
            #mail.debug: "true"
